### ISSUE TITLE
AttributeError in cv2.cvtColor

### ISSUE THREAD

**Issue by TheMikeyR** [akisato-/pySaliencyMap#2]
Hello, I'm using Python 2.7.11, Anaconda 4.0.0 with OpenCV 3.1.0 and I've found an attribute error in your code, in file `pySaliencyMap.py` when using the version above
In the following line; `I = cv2.cvtColor(src, cv2.cv.CV_BGR2GRAY)`
The code run great when this is edited to be:
`I = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)`

**Comment by akisato-** [comment]
Thank you very much for pointing out a flaw in my code. I have fixed it. See https://github.com/akisato-/pySaliencyMap/commit/fd67f05ee3a6b902e518f5062e1ff6c28078978c
